rules/klayout/lvs: try multiple netlist formats
efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr pull request #26
Opened 2023-02-07 18:48 UTC by proppy

Related: https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pr/pull/99 https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pr/issues/101 https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pv/issues/39 https://github.com/RTimothyEdwards/open_pdks/issues/346

This allow to discover LVS netlists generated by xschem with their default extension (`.spice`).

2023-02-10 12:21 UTC, atorkmabrains requested changes

2023-02-10 12:21 UTC, atorkmabrains commented on rules/klayout/lvs/gf180mcu.lvs
> +  candidates = exts.map{|ext| "#{source.cell_name}.#{ext}"}
@proppy Could you please remove 'ngspice' as we can't use the netlist used for simulation for LVS?

2023-02-15 08:14 UTC, atorkmabrains commented on rules/klayout/lvs/gf180mcu.lvs
> +  candidates = exts.map{|ext| "#{source.cell_name}.#{ext}"}
@proppy ?

2023-02-15 09:08 UTC, proppy commented
PTAL

2023-02-15 09:49 UTC, atorkmabrains approved these changes
Thanks for the update.

2023-02-15 09:49 UTC, merged